class UIColours:
    BLACK = '#000000'
    WHITE = '#ffffff'
    RED = '#cc0000'
    PALE_RED = '#ff8888'
    DARK_GREY = '#222222'
    DARKISH_GREY = '#444444'
    GREY = '#666666'
    DARK_BLUE = '#000066'
    EYE_BLUE = "#3388ff"
    EYE_BLUE_FADED = "#66AAff"
    YELLOW = "#ffff00"


class ThemeColours:
    BACKGROUND = UIColours.DARK_GREY
    MIDGROUND = UIColours.GREY
    SELECTED_ROW_BACKGROUND = UIColours.EYE_BLUE_FADED
    ROW_BACKGROUND = UIColours.DARKISH_GREY
    TITLE_BACKGROUND = UIColours.DARK_GREY
    TEXT = UIColours.WHITE
    LINK = UIColours.EYE_BLUE
    BUTTON_TEXT = UIColours.EYE_BLUE
    HIGHLIGHT_COLOR = UIColours.EYE_BLUE
    ATTENTION_COLOR = UIColours.RED
    BUTTON_TEXT_DEFAULT= UIColours.BLACK
    TOOLTIP_BACKGROUND = UIColours.EYE_BLUE_FADED
    ERROR_COLOR = UIColours.PALE_RED
    WARNING_COLOR = UIColours.YELLOW
